services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn zoo.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - ./:/home/zoo
        ports:
            - 8000:8000
        environment:
            DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/zoo
        depends_on:
            - db

    db:
        image: postgres:15.3
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=zoo
