# $schema: https://squidfunk.github.io/mkdocs-material/schema.json

site_name: zoo
nav:
    - index.md
    - Contributing 🤝: contributing.md
    - Infrastructure 🏗: infrastructure.md
    - Project Structure 📂: project_structure.md
    - OpenAPI Docs ✨: openapi.md
theme:
    favicon: https://raw.githubusercontent.com/juftin/juftin/main/static/juftin.png
    logo: https://raw.githubusercontent.com/juftin/juftin/main/static/juftin.png
    name: material
    features:
        - navigation.tracking
        - content.code.annotate
        - content.code.copy
        - navigation.indexes
    palette:
        - media: "(prefers-color-scheme: light)"
          scheme: default
          accent: purple
          toggle:
              icon: material/weather-sunny
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
              icon: material/weather-night
              name: Switch to light mode
    icon:
        admonition:
            abstract: material/file-code
            tip: material/fire
            note: fontawesome/regular/note-sticky
repo_url: https://github.com/juftin/zoo
repo_name: zoo
edit_uri: blob/main/docs/
site_author: Justin Flannery
remote_branch: gh-pages
copyright: Copyright © 2023 Justin Flannery
extra:
    generator: false
markdown_extensions:
    - toc:
          permalink: "#"
    - pymdownx.snippets:
          base_path:
              - !relative $config_dir
    - pymdownx.magiclink
    - attr_list
    - md_in_html
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - markdown.extensions.attr_list
    - pymdownx.keys
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.tilde
    - admonition
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
plugins:
    - search
    - markdown-exec
