"""
Generic database utility models
"""

import datetime

from pydantic import ConfigDict, Field

from zoo.schemas.base import ZooModel


class Health(ZooModel):
    """
    Health model
    """

    status: str = Field(description="The status of the application")
    code: int = Field(description="The status code of the response")
    timestamp: datetime.datetime = Field(
        description="The timestamp of the response generated by the server"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "status": "OK",
                    "code": 200,
                    "timestamp": "2021-05-01T12:00:00.000000+00:00",
                }
            ]
        }
    )
