name: Lint

on:
    pull_request:
        branches: ["**"]

jobs:
    lint:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ matrix.python }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - name: Set up Github Workspace
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Python Environment 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"
            - name: Install Hatch
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -q hatch pre-commit
                  hatch env create
                  hatch --version
            - name: Lint
              id: lint
              continue-on-error: true
              run: |
                  echo "::add-matcher::.github/workflows/matchers/flake8.json"
                  hatch run lint:style
                  echo "::remove-matcher owner=flake8::"
            - name: Code Checker
              id: check
              continue-on-error: true
              run: |
                  echo "::add-matcher::.github/workflows/matchers/mypy.json"
                  hatch run lint:typing
                  echo "::remove-matcher owner=mypy::"
            - name: Raise Errors For Linting Failures
              if: |
                  steps.lint.outcome != 'success' ||
                    steps.check.outcome != 'success'
              run: |
                  echo "Lint: ${{ steps.lint.outcome }}"
                  echo "Check: ${{ steps.check.outcome }}"
                  exit 1
